name: Run Python Script

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to click "Run workflow" manually

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute script with Secrets
      env:
        # Change 'YOUR_GITHUB_SECRET_NAME' to your actual GitHub secret name
        MY_API_KEY: ${{ secrets.MY_API_KEY}} 
      run: python fundamentals.py
